"""empty message

Revision ID: 152baedfe81e
Revises: 
Create Date: 2018-11-02 12:22:05.643701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '152baedfe81e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_posted', sa.DateTime(), nullable=True),
    sa.Column('distance', sa.Float(), nullable=True),
    sa.Column('run_time', sa.Integer(), nullable=True),
    sa.Column('calories_burned', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_run_date_posted'), 'run', ['date_posted'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_run_date_posted'), table_name='run')
    op.drop_table('run')
    # ### end Alembic commands ###
