"""empty message

Revision ID: e365dcf8d346
Revises: 652440221a80
Create Date: 2018-11-05 16:06:09.936671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e365dcf8d346'
down_revision = '652440221a80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('run', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'run', 'user', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'run', type_='foreignkey')
    op.drop_column('run', 'owner_id')
    # ### end Alembic commands ###
